"""
Parse mldr.js (extracted from howardgrubb.co.uk MLDR Road age-grading calculator)
and emit factors.py — a pure-data Python module with one dict per factor set.

Run this whenever mldr.js is refreshed from the source page.
"""

import re
from pathlib import Path


JS_PATH = Path(__file__).parent / "mldr.js"
OUT_PATH = Path(__file__).parent / "factors.py"


def parse_js(js_text: str) -> dict:
    """Return {set_name: {"ages":[...], "events":[{name,distance_km,standard_sec,age_factors:[]}, ...]}}."""

    # 1) Find every "var <name> = new Factors();" declaration to seed the dict.
    set_names = re.findall(r"\bvar\s+(\w+_facs)\s*=\s*new\s+Factors\s*\(\s*\)\s*;", js_text)
    out = {name: {"ages": [], "events": []} for name in set_names}

    # 2) For each set, capture its addAges(new Array(...)) call.
    for name in set_names:
        m = re.search(
            rf"{re.escape(name)}\.addAges\s*\(\s*new\s+Array\s*\(([^)]*)\)\s*\)\s*;",
            js_text,
        )
        if not m:
            raise RuntimeError(f"No addAges() for {name}")
        out[name]["ages"] = [int(x) for x in m.group(1).split(",") if x.strip()]

    # 3) Each addEvent(new facrow("name", dist_km, std_sec, f1, f2, ...))
    pat = re.compile(
        r"(\w+_facs)\.addEvent\s*\(\s*new\s+facrow\s*\(\s*"
        r'"([^"]+)"\s*,\s*'           # event name
        r"([0-9.]+)\s*,\s*"            # distance km
        r"([0-9.]+)\s*,\s*"            # standard seconds (open-age WR/standard)
        r"([0-9eE.\-+,\s]+)"           # the age factors
        r"\)\s*\)\s*;",
        re.DOTALL,
    )
    for m in pat.finditer(js_text):
        set_name = m.group(1)
        event = {
            "name": m.group(2),
            "distance_km": float(m.group(3)),
            "standard_sec": float(m.group(4)),
            "age_factors": [float(x) for x in m.group(5).split(",") if x.strip()],
        }
        out[set_name]["events"].append(event)
        if len(event["age_factors"]) != len(out[set_name]["ages"]):
            raise RuntimeError(
                f"Age factor count mismatch for {set_name}/{event['name']}: "
                f"{len(event['age_factors'])} factors vs {len(out[set_name]['ages'])} ages"
            )

    # Drop empty sets (defensive — shouldn't happen).
    return {k: v for k, v in out.items() if v["events"]}


def emit_python(tables: dict, out_path: Path):
    lines = [
        '"""Auto-generated by extract_factors.py — do not edit by hand."""',
        "",
        "# {set_name: {ages, events: [{name, distance_km, standard_sec, age_factors}]}}",
        "FACTOR_SETS = {",
    ]
    for set_name, body in tables.items():
        lines.append(f'    "{set_name}": {{')
        lines.append(f'        "ages": {body["ages"]!r},')
        lines.append('        "events": [')
        for ev in body["events"]:
            lines.append("            {")
            lines.append(f'                "name": {ev["name"]!r},')
            lines.append(f'                "distance_km": {ev["distance_km"]!r},')
            lines.append(f'                "standard_sec": {ev["standard_sec"]!r},')
            lines.append(f'                "age_factors": {ev["age_factors"]!r},')
            lines.append("            },")
        lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines))


def main():
    js = JS_PATH.read_text()
    tables = parse_js(js)
    emit_python(tables, OUT_PATH)
    print(f"Wrote {OUT_PATH}")
    for name, body in tables.items():
        print(f"  {name}: {len(body['events'])} events, {len(body['ages'])} ages")


if __name__ == "__main__":
    main()
